AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'veryfirstlambda

  Sample SAM Template for veryfirstlambda

  '
Globals:
  Function:
    Timeout: 3
Resources:
  VehiclesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-test-bucket-vehiclestore/ad8dac4460d7a66783cddccee558373f
      Handler: lambda.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies:
      - DynamoDBCrudPolicy:
          TableName: RebowskiVehicleStore
      Environment:
        Variables:
          TABLE_NAME: RebowskiVehicleStore
      Role: arn:aws:iam::668487117877:role/MyVehicleServiceLambdaRole
      Events:
        InsertVehicle:
          Type: Api
          Properties:
            Path: /MyVehicleStore/vehicles
            Method: PUT
        GetVehicleDetails:
          Type: Api
          Properties:
            Path: /MyVehicleStore/vehicles/{vin}
            Method: GET
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RebowskiVehicleStore
      AttributeDefinitions:
      - AttributeName: vin
        AttributeType: S
      KeySchema:
      - AttributeName: vin
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
