AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  veryfirstlambda

  Sample SAM Template for veryfirstlambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  VehiclesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    # sets the function
    Properties:
      CodeUri: ./code
      Handler: lambda.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy: #Gives read and write permission to DynamoDB on-demand backups for a table. see:https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#dynamo-db-crud-policy
            TableName: 'RebowskiVehicleStore'
      Environment:
        Variables:
          TABLE_NAME: 'RebowskiVehicleStore'
      Role: arn:aws:iam::668487117877:role/MyVehicleServiceLambdaRole #lets the lambda permissions and operation in a controlled context?
      Events:
        InsertVehicle: #defining type: api sets automatically the api gateway;
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /MyVehicleStore/vehicles
            Method: PUT
        GetVehicleDetails:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /MyVehicleStore/vehicles/{vin}
            Method: GET
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'RebowskiVehicleStore'
      AttributeDefinitions:
        - AttributeName: vin
          AttributeType: S
      KeySchema:
        - AttributeName: vin
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
